---
title: "vizWithSCE"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vizWithSCE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

*vizWithSCE* is an R package that allows users to ....

# Run DESeq2 to obtain bulk DE results

We load gene-summarized RNA-seq counts.

```{r}
library(airway)
data(gse)
levels(gse$condition) <- c("untrt", "trt")
```

Here we filter to at least 3 samples with a count of 10 or higher.

```{r}
library(DESeq2)
dds <- DESeqDataSet(gse, design = ~donor + condition)
keep <- rowSums(counts(dds) >= 10) >= 3
dds <- dds[keep,]
```

```{r}
dds <- DESeq(dds)
res <- results(dds)
rownames(res) <- sub("\\..*","",rownames(res))
```

# Run `integrateWithSingleCell`

```{r}
source("R/integrate.R")
dat <- integrateWithSingleCell(res, dds)
```

# Label cell types or clusters

```{r}
library(org.Hs.eg.db)
library(SingleR)
sce2 <- sce
rownames(sce2) <- mapIds(org.Hs.eg.db, rownames(sce2), "SYMBOL", "ENSEMBL")
ref <- BlueprintEncodeData()
pred <- SingleR(test=sce2, ref=ref, labels=ref$label.main)
table(pred$labels)
table(pred$labels, colLabels(sce))
```

Also show example with clustering...

# Use *vizWithSCE* for visualization 

```{r}
library(vizWithSCE)
vizWithSCE(dat, which=1)
```

# Session info

```{r}
sessionInfo()
```
